l_include:
#-#    - '神价'
#-#    - '手慢无'
#- '优惠券'
#-#    - '小牛'
#-    - '科克兰'
#-#    - '无盐'
#-#    - '加油卡'
    - '好奇'
#-#    - '胎压'
#-#    - '票据'
#-#    - '网件'
    - '树莓派'
    - '牛腱子'
#-#    - '爱乐普'
#-#    - 'eneloop'
#-#    - '磁力'
#-#    - '帝都'

l_exclude:
    - '挡风被'
    - '权利游戏'
    - '演唱会'
    - '权利的游戏'
    - '教材'
    - '爱普生'
    - '手电'
    - '猫用'
    - '犬用'
    - '速干裤'
    - '风扇'
    - '消毒片'
    - '三角裤'
    - '战术裤'
    - '衬衫'
    - '婴幼儿'
    - '内裤'
    - '微单'
    - '探鱼器'
    - '龙头'
    - '即食面'
    - '往返机票'
    - '五星酒店'
    - '小夜灯'
    - '茶壶'
    - '善存'
    - '布书'
    - '象印'
    - '护理油'
    - '裙子'
    - '醒酒'
    - '膨胀'
    - '螺丝'
    - '百香果'
    - '油茶'
    - '套头毛衣'
    - '储物柜'
    - '储物箱'
    - '衬衣'
    - '香水'
    - '泸州老窖'
    - '防护乳'
    - '农夫山泉'
    - '润肤霜'
    - '杏仁露'
    - '保温杯'
    - '一加'
    - '张家界'
    - '自由行'
    - '保湿'
    - '饮水机'
    - '过桥米线'
    - '幼犬'
    - '椅子'
    - '退热贴'
    - '腰包'
    - '抓绒衣'
    - '阿胶枣'
    - '办公椅'
    - '金六福'
    - '柔湿巾'
    - '白咖啡'
    - '使命召唤'
    - '蜂蜜'
    - '风衣'
    - '洋河蓝色经典'
    - '夏威夷果'
    - '脱毛器'
    - '哺乳'
    - '羊毛'
    - 'BECBAS'
    - '左旋肉碱'
    - '压缩衣'
    - '压缩裤'
    - '烘干'
    - '薄荷糖'
    - '虎牌'
    - '啪啪通'
    - '鱼肝油'
    - '护肘'
    - '额定'
    - '时装表'
    - '硒鼓'
    - '披肩'
    - '吉隆坡'
    - '棉花糖'
    - '乳垫'
    - '网线'
    - '灭蚊灯'
    - '燃气灶'
    - '浴霸'
    - '美肤'
    - '电锤'
    - '雨刮器'
    - '莎士比亚'
    - '纳尼亚传奇'
    - '海底两万里'
    - '天文望远镜'
    - '玻璃胶'
    - '瑞士军刀'
    - '舒肩枕'
    - '巴旦木'
    - 'iMac'
    - '散热器'
    - '游戏台式主机'
    - '雷神'
    - '支架'
    - '哑铃'
    - '助听器'
    - '健安喜'
    - '模组电源'
    - '三步梯'
    - '训练鞋'
    - '插座'
    - '碳粉'
    - '荣耀'
    - '鸭锁骨'
    - '雷克沙'
    - '普吉'
    - '威海'
    - '往返'
    - '雷朋'
    - '意大利面'
    - '护肤'
    - '点烟器'
    - '洗车'
    - '碧然德'
    - '乐而雅'
    - '蟑螂'
    - '四大名著'
    - '趣拍得'
    - '竹炭'
    - '曦瓜'
    - '教材用书'
    - '婺源'
    - '井冈山'
    - '移动电源'
    - '小脚裤'
    - '森海塞尔'
    - 'DE&E'
    - '暖奶器'
    - '儿童餐椅'
    - '汽油添加剂'
    - '复印纸'
    - '山地车'
    - '龟牌'
    - 'SK-II'
    - 'Zamberlan'
    - '考试'
    - '公务员'
    - '种菜'
    - '挂钟'
    - '北京电信'
    - '玻璃杯'
    - '晴雨伞'
    - '氧气机'
    - '车充'
    - '切菜'
    - '茶'
    - '螺蛳粉'
    - '置物架'
    - 'dyson'
    - '零食杯'
    - '骨瓷'
    - '爆米花'
    - '汽车脚垫'
    - '吊灯'
    - '徒步鞋'
    - '马桶'
    - '风火轮'
    - '原汁机'
    - '凉席'
    - '空气炸锅'
    - '冷静王'
    - '垃圾桶'
    - '码表'
    - '闷烧'
    - '老鼠'
    - '钢化膜'
    - '吧台'
    - '碎纸机'
    - '暖手宝'
    - '交行'
    - '工行'
    - '疏通'
    - '学习桌椅'
    - '日加满'
    - '水冷'
    - '洗鼻器'
    - '毛巾'
    - '狼爪'
    - '背包'
    - '玻尿酸'
    - '牙线'
    - '双立人'
    - 'OSPREY'
    - '卫衣'
    - '眼霜'
    - '手指饼'
    - '菲比'
    - '步步高'
    - '教辅'
    - '盐水'
    - 'Halo'
    - '彼得兔的故事'
    - '增肌'
    - '棉签'
    - '筷子'
    - '诗经'
    - '四书'
    - '成人用品'
    - '花洒'
    - '音频线'
    - 'usb延长线'
    - '震动棒'
    - '麦克风'
    - '中老年'
    - '电脑椅'
    - '压缩裤'
    - '枣夹核桃'
    - '可可粉'
    - '温度计'
    - '添柏岚'
    - 'Timberland'
    - '杀虫剂'
    - '叠叠乐'
    - '洗面'
    - '破壁'
    - '波特'
    - '霜'
    - '糖果'
    - '航拍'
    - '四轴'
    - '普吉岛'
    - '机顶盒'
    - 'winner'
    - 'VICTORINOX'
    - '维氏'
    - '衣柜'
    - '护膝'
    - '护腕'
    - '光波炉'
    - 'iPhone'
    - '口红'
    - '肾宝'
    - '防晒'
    - '车载'
    - '产后'
    - '控油'
    - '鞋柜'
    - '三百首'
    - '面霜'
    - '短裤'
    - '水枪'
    - '台式机电源'
    - '商务'
    - 'Sagami'
    - '项链'
    - 'NERF'
    - '打气筒'
    - '鞋油'
    - '牛排'
    - 'G5'
    - '女装'
    - '男装'
    - '连帽套头'
    - '西门子'
    - '烘衣机'
    - '电脑包'
    - '吸奶器'
    - '长尾夹'
    - '优衣库'
    - '山地自行车'
    - '小马过河'
    - '刀具组合'
    - '球拍'
    - '科勒'
    - '水蜡'
    - '钢铁侠'
    - '星球大战'
    - '漫威'
    - '琵琶腿'
    - '心家宜'
    - '潜水艇'
    - '甲醛'
    - '电子黑板'
    - '酱'
    - '机械表'
    - '女童'
    - '爱诗普霖'
    - '洗衣粉'
    - '香肠'
    - '电子辞典'
    - '速干内裤'
    - '周易'
    - '手镯'
    - '衣领净'
    - '泡椒'
    - '老板'
    - '网球'
    - '妈妈包'
    - '礼之尚'
    - '柔顺剂'
    - '跑步机'
    - 'Topsky'
    - '翅根'
    - '年糕'
    - '鸡爪'
    - '体脂'
    - '耳带'
    - '登山'
    - '针灸'
    - '机器人'
    - '伏特加'
    - '黑啤'
    - '狗零食'
    - '拖拉机'
    - '搅拌车'
    - '推土机'
    - '压路机'
    - '矫正带'
    - '油壶'
    - '刀具'
    - '电喷'
    - '养生'
    - '军刀'
    - '电路积木'
    - 'SONMUSE'
    - '声缪斯'
    - '欢乐谷'
    - '晶彩'
    - '迪拜'
    - '卫生巾'
    - '人字拖'
    - '门票'
    - '跟团游'
    - '纸杯'
    - '自热米饭'
    - '压缩商品'
    - '压缩干粮'
    - '跳绳'
    - '慢回弹'
    - '消毒柜'
    - '滤水壶'
    - '周杰伦'
    - '忍者'
    - '博朗'
    - '摩恩'
    - '滋润霜'
    - '空调'
    - '路由器'
    - '电热水壶'
    - '奥马'
    - '小蜜蜂'
    - '果冻'
    - '体重'
    - '除螨'
    - '棒棒糖'
    - '护目'
    - '故事机'
    - '早教'
    - '爬行'
    - '足疗'
    - '自然唤醒'
    - '工具套装'
    - '滑雪'
    - '领带'
    - '英特尔'
    - '得力'
    - '软糖'
    - '土鸡'
    - '鸡蛋'
    - '枕头'
    - '地毯'
    - '餐桌'
    - '修复霜'
    - '手表'
    - '餐具'
    - '虾片'
    - '小麦啤'
    - '鸭脖'
    - '紧身'
    - '筒灯'
    - '射灯'
    - '蛋糕'
    - '巧克力'
    - '洗碗机'
    - '哈利波特'
    - '飞侠'
    - '犬'
#-#    - '猫'
    - '女表'
    - '男表'
    - '腕表'
    - '犬粮'
    - '猫粮'
#-#    - '每日坚果'
    - '蒸汽'
    - '航线'
    - '旅行'
    - '狗粮'
    - '水星网络'
    - '面包'
    - '饮料'
    - '无痕'
    - '黑芝麻糊'
    - '单鞋'
    - '马桶盖'
    - 'GUCCI'
    - '单肩'
    - '三只松鼠'
    - '浴袍'
    - '圣诞树'
    - '日元'
    - '女子'
    - '女士'
    - '女式'
    - '女款'
    - '良品铺子'
    - '手帕纸'
    - '游戏本'
    - '惠普'
    - '去腥'
    - '巴法络'
    - '交换机'
    - '双肩包'
    - '汀'
    - '航空'
    - '雾化器'
    - '伞车'
    - '美特斯邦威'
    - '男士护肤'
    - '创口'
    - '宝路'
    - '狗不理'
    - '羽绒'
    - '多肉'
    - '手机支架'
    - '打火机'
    - '汽车座椅'
    - '划船器'
    - '极路由'
    - '睡袋'
    - '苏打'
    - '汽水'
    - '雪碧'
    - '可乐'
    - '三星'
    - '乳胶'
    - '辣条'
    - '床'
    - '调理'
    - '盆栽'
    - '毛衣'
    - '挂钩'
    - '老花镜'
    - '气吹'
    - '眼镜架'
    - '勺子'
    - '脚链'
    - '眼药水'
    - '滴眼液'
    - '铁观音'
    - '镜框'
    - '益生菌'
    - '开心果'
    - '速食'
    - '皮衣'
    - '喷雾'
    - '绒被'
    - '麻辣'
    - '血糖'
    - '浴巾'
    - '疤痕'
    - '粘鼠板'
    - '雅马哈'
    - '护舒宝'
    - '洁肤'
    - '除臭'
    - '烘干'
    - '薯片'
    - '挂烫机'
    - '加湿器'
    - '西装'
    - '内衣'
    - '邮差包'
    - '台湾'
    - '日本'
    - '鞋垫'
    - 'nubia'
    - '努比亚'
    - '小龙虾'
    - '波司登'
    - '欧乐B'
    - '摩托罗拉'
    - '微星'
    - '吊坠'
    - '思华洛奇'
    - '电子秤'
    - '联想'
    - '陶瓷刀'
    - '润喉糖'
    - '补水'
    - '魅族'
    - '干吃面'
    - '背包'
    - '格里高利'
    - '闷烧'
    - '戴尔'
    - '签证'
    - '邮轮'
    - 'TP-LINK'
    - '普联'
    - '运动鞋'
    - '睡衣'
    - '百草味'
    - '迪士尼'
    - '罐头'
    - '被子'
    - '统一'
    - '好丽友'
    - '香樟'
    - '飞狮'
    - '雷摄'
    - '封口'
    - '扫地机'
    - '鼻毛'
    - '凯立德'
    - '还原'
    - '蜜饯'
    - '凝霜'
    - '冲锋'
    - '周大生'
    - '防晒霜'
    - '训练裤'
    - '洗头水'
    - '斯凯奇'
    - '瑞士三角'
    - '乐视'
    - '凉鞋'
    - '收纳'
    - '奇虎360'
    - '红双喜'
    - 'FOSSIL'
    - '唐狮'
    - 'kindle'
    - 'Kindle'
    - '科沃斯'
    - '兰若诗'
    - '资生堂'
    - '豆腐干'
    - '5610'
    - '5600'
    - '1000'
    - '白啤'
    - 'DDR4'
    - '探路者'
    - 'DOD'
    - '凌度'
    - '李宁'
    - '坐便器'
    - '铅笔'
    - '自动铅笔'
    - '滑板车'
    - '头枕'
    - '白兰地'
    - '酸奶机'
    - '洋酒'
    - '广角镜'
    - '电暖器'
    - '取暖器'
    - '黄油'
    - '转换器'
    - 'PlayStation'
    - '电源插座'
    - '百洁布'
    - '清新剂'
    - '面条机'
    - '葡萄糖'
    - '笔记本电脑'
    - '抽油烟机'
    - '挂衣架'
    - '电动牙刷'
    - '女士内衣'
    - '女士香水'
    - '四件套'
    - '炒货'
    - '周生生'
    - '兰花豆'
    - '冲锋衣'
    - '后备箱'
    - '大头鞋'
    - '腰靠'
    - '方巾'
    - '黄玉米'
    - '短袜'
    - '身体乳'
    - '丝袜'
    - '液晶电视'
    - '眼镜'
    - '钙尔奇'
    - '羽绒服'
    - '猕猴'
    - '鸭子造型'
    - '打底裤'
    - '面膜'
    - '乖乖鸭'
    - '牛仔裤'
    - '料理机'
    - '休闲鞋'
    - '杜蕾斯'
    - '套票'
    - '按摩贴'
    - '机械键盘'
    - '海盗船'
    - '海尔'
    - '创口贴'
    - '跑鞋'
    - '跑步鞋'
    - '手链'
    - '黄金'
    - '纯金'
    - '外套'
    - '小白'
    - '衣架'
    - '护手霜'
    - '沙发'
    - '杀蟑'
    - '夹克'
    - '分裤'
    - '保温'
    - '茶叶'
    - '中兴'
    - '营养粉'
    - '干衣机'
    - '挎包'
    - '膏'
    - '软弹枪'
    - '火线营'
    - '暖风机'
    - '热水袋'
    - '手机壳'
    - '扫地机器人'
    - '酵素粉'
    - '弹弓'
    - '口香糖'
    - '手套'
    - '刚需'
    - '金苏梅'
    - '防潮垫'
    - '平底鞋'
    - '高跟鞋'
    - '衫'
    - '靴'
    - '笔'
    - '手写板'
    - '键盘'
    - '鼠标'
    - '广发'
    - '浦发'
    - '洗发'
    - '护发'
    - '裙'
    - '绿茶'
    - '直升机'
    - '播放器'
    - '显示器'
    - 'Mate8'
    - 'P8'
    - 'iphone'
    - 'IPHONE'
    - '沐浴露'
    - '剃须刀'
    - '苹果'
    - '气雾剂'
    - '滋养'
    - '热熏'
    - '仰卧起坐'
    - '限华南'
    - '限上海'
    - '视觉激发卡'
    - '桂圆'
    - '森马'
    - '分线器'
    - '耳机'
    - '眉笔'
    - '眉膏'
    - '休闲运动鞋'
    - '安儿乐'
    - '水槽'
    - '精华'
    - '冲击钻'
    - 'E卡口'
    - '背包'
    - '镜头'
    - '三脚架'
    - '尼康'
    - '宾得'
    - '活肤霜'
    - '佳能'
    - '净化器'
    - '理发器'
    - '亚瑟士'
    - '兰蔻'
    - '毛被'
    - '提臀'
    - '无人机'
    - '粉底'
    - '乳胶枕'
    - '美容'
    - '耐克'
    - '阿迪达斯'
    - '驱蚊'
    - '羽毛球'
    - '威士忌'
    - '葡萄酒'
    - '啤酒'
    - '保温'
    - '不粘锅'
    - '牛奶'
    - '纯牛奶'
    - '咖啡'
    - '电视'
    - '摄像头'
    - '机箱'
    - '台灯'
    - '彩电'
    - '冰箱'
    - '音箱'
    - '洗衣机'
    - '水壶'
    - '调奶'
    - '鱼缸'
    - '拉面'
    - '冬阴功'
    - '取暖'
    - '洗衣液'
    - '健腹'
    - '猪肋'
    - '回力'
    - '拖把'
    - '太阳镜'
    - '制氧机'
    - '皮带'
    - '腰带'
    - '能量棒'
    - '护颈枕'
    - '电饭煲'
    - 'V领'
    - '榨汁机'
    - '打蛋器'
    - 'LINKSYS'
    - 'TP'
    - '净水器'
    - '鸭嘴'
    - '腿套'
    - '耳温'
    - '爽肤水'
    - '额温'
    - '避孕套'
    - '护理垫'
    - '豆豉'
    - '吸顶灯'
    - '冰淇淋'
    - '刨冰机'
    - '奶粉'
    - '电吹风'
    - '血糖仪'
    - '吸尘器'
    - '数码相机'
    - '乳液'
    - '胶囊'
    - '玉兰油'
    - '葵花籽油'
    - '电水壶'
    - '唐卡'
    - '吸乳器'
    - 'LELO'
    - '电烤箱'
    - '冈本'
    - '心率表'
    - '母婴'
    - '消毒器'
    - 'NB'
    - '婴儿湿巾'
    - '腌菜'
    - '腐乳'
    - '老干妈'
    - '猪肉'
    - '西服'
    - '充气'
    - '电磁炉'
    - '汤面'
    - '晾衣'
    - '文胸'
    - '袜'
    - '方便面'
    - '皮鞋'
    - '面包机'
    - '旋风拖'
    - '安全座椅'
    - '费雪'
    - '盈通'
    - '磨豆机'
    - '膳魔师'
    - '亨氏'
    - '新安怡'
    - '胶囊'
    - '豆浆机'
    - '欧莱雅'
    - '多美滋'
    - '柔肤水'
    - '热水器'
    - '花生油'
    - '玉米油'
    - '润肤乳'
    - '沐浴乳'
    - '洁面乳'
    - '音响'
    - 'OLAY'
    - '血压计'
    - '拼插'
    - '化妆'
    - '卸妆'
    - '相机'
    - '漱口水'
    - '隐形眼镜'
    - '欧姆龙'
    - '笔记本'
    - '拉杆箱'
    - '橄榄油'
    - '乐扣'
    - '雀巢'
    - '绘儿乐'
    - '衣柜'
    - '酒'
    - '显卡'
    - '好孩子'
    - '施华蔻'
    - '啤酒'
    - '泡沫'
    - '床品'
    - 'Schneider'
    - '施耐德'
    - '嘉宝'
    - '缝纫机'
    - '牙刷'
    - '饼干'
    - '电压力锅'
    - '电饼铛'
    - '推车'
    - '搅拌机'
    - '料理机'
    - '婴儿卫生湿巾'
    - '威联通'
    - '心率表'
    - '米粉'
    - '床品'
    - '蜜丝佛陀'
    - '机箱'
    - '泰迪熊'
    - '泳帽'
    - '歌瑞尔'
    - '衣帽架'
    - '内增高鞋'
    - '创可贴'
    - '护发素'
    - '旁氏'
    - '炒锅'
    - '星球大战'
    - '美妆'
    - '洁面仪'
    - '吊床'
    - '记忆枕'
    - '雷达'
    - '乳酸菌'
    - '刻刀'
    - '运动饮料'
    - '蛋白粉'
    - '胶原蛋白'
    - '美津浓'
    - '地球妈妈'
    - '压力锅'
    - '火锅'
    - '电子称'
    - '浴盆'
    - '银装'
    - '奶瓶'
    - '休闲裤'
    - '金纺'
    - '拖鞋'
    - '签字笔'
    - '红点'
    - '连衣裙'
    - '垃圾处理器'
    - '驼毛'
    - '护膝'
    - '露得清'
    - '溯溪鞋'
    - '固态'
    - '薇姿'
    - '蔻姿'
    - '创见'
    - '速比涛'
    - '雅诗兰黛'
    - '篮球'
    - '足球'
    - '羽毛球'
    - '卷发'
    - '烧烤盘'
    - '啫喱'
    - '红茶'
    - '维生素'
    - '进口食品'
    - '坐垫'
    - '土拨鼠'
    - '始祖鸟'
    - '沙宣'
    - '柔肤露'
    - '九阳'
    - '收音机'
    - '松下'
    - '主板'
    - '套锅'
    - '爱仕达'
    - '高丝'
    - '牙膏'
    - '座便器'
    - '乐高'
    - '机油'
    - '微软'
    - '电钻'
    - '变形金刚'
    - '芭比'
    - '暴雪'
    - '追踪器'
    - 'SEKKISEI'
    - '手环'
    - '轮滑'
    - '施华洛世奇'
    - '显示器'
    - '平板电脑'
    - '油烟机'
    - '钱包'
    - '假发'
    - '精华液'
    - '床垫'
    - '饮用水'
    - '机票'
    - '宠物'
    - '地理'
    - '护臀膏'
    - '按摩'
    - '胎盘'
    - '孕妇'
    - '酥'
    - '美发'
    - '电暖'
    - '双人'
    - '煎锅'
    - '修剪'
    - '茶'
    - '鸡汤'
    - '消化饼'
    - '伊花坊'
    - '女宝宝'
    - '北田'
    - '溜冰鞋'
    - 'SSE-BTR1'
    - '音响'
    - '板鞋'
    - '内墙漆'
    - '电风扇'
    - '电熨斗'
    - '雪糕'
    - '密封机'
    - '斯波帝卡'
    - '楼兰蜜语'
    - '汤臣倍健'
    - '北极狼'
    - '洗澡刷'
    - '椰子油'
    - '牛轧糖'
    - 'WNDR4300'
    - '仙餐牌'
    - '香薰'
    - '考研'
    - '健力多'
    - '矿泉水'
    - '棉服'
    - '电热毯'
    - '安全套'
    - '投影'
    - '试卷'
    - '牛肉丝'
    - '洗面奶'
    - '红肠'
    - '书包'
    - '骑行'


